### ISSUE TITLE
加密算法部分

### ISSUE THREAD

**Issue by zhaozhao626** [SamuelGong/FLASHE#4]
打扰到您了，请问加密算法是否采用的是AES算法呢？如果是用的AES，可是AES算法应该不是同态的吧。

**Comment by SamuelGong** [comment]
Dear @zhaozhao626,

Thank you for your interest in our paper! No, we are not using AES to encrypt. In other words, to encrypt plaintext `x`, we are not computing `c = AES(x)`. Instead, we are computing `c = (x + AES(some_seed)) mod some_big_number`, where the exact meaning of this formula can be referred to the arXiv [paper](https://github.com/SamuelGong/FLASHE/blob/master/README.md#). Hope this can help you!
