### ISSUE TITLE
NameError: name 'pickle' is not defined

### ISSUE THREAD

**Issue by zhaozhao626** [SamuelGong/FLASHE#5]
作者，您好！
在https://github.com/SamuelGong/FLASHE/blob/master/encrypt_test/final_big_table.ipynb中出现了
NameError: name 'pickle' is not defined
![image](https://user-images.githubusercontent.com/82107239/217495469-1c203aa7-7e5e-4a7f-886f-d8c7aa016704.png)
我翻阅您的文件，并没有定义这个对象，请问这个变量是什么？
期待您的回复！

**Comment by SamuelGong** [comment]
Thanks for the catch! There happened to miss a package import for `pickle`. To fix it, you only need to add one line of code `import pickle` anywhere before the line `a_b = pickle.dumps(a_c)`.

I have also fixed the original file and you can also pull and apply the change immediately.

**Comment by zhaozhao626** [comment]
谢谢您的帮助！
