### ISSUE TITLE
issue about “element_bits,int_bits,additional_bits"

### ISSUE THREAD

**Issue by zhaozhao626** [SamuelGong/FLASHE#6]
您好,作者!
很抱歉又一次打扰到您.
在您的代码中:https://github.com/SamuelGong/FLASHE/blob/master/encrypt_test/final_big_table.ipynb 请问element_bits,int_bits,additional_bits分别代表什么?  对这些位数的设置有要求吗?  
以及在https://github.com/SamuelGong/FLASHE/blob/master/federatedml/secureprotol/jzf_quantize.py 中 关于  batch_size = int_bits // element_bits 这个又是怎么去理解呢?
期待您的回复!

**Comment by SamuelGong** [comment]
Hi there,

Sorry for the confusion and ambiguity caused.

### Meaning of the Variables in `final_big_table`

Specifically, `element_bits` is a configurable parameter which means **how many bits do you wish to use for representing a floating-point number**, whenever quantization is needed for encryption (i.e., FLASHE/Paillier/BFV). For example, setting it as `16` means that when using the above-mentioned encryption scheme, a floating-point number will be quantized into a 16-bit integer.

In the original `final_big_table`, both `additional_bits` and `int_bits` are defined dynamically, i.e., a user is not expected to configure them. First, `additional_bits` means **how many bits we should additionally preserve for the sum to avoid overflowing**. As a concrete example, suppose that you have two 3-bit quantized integers: `4` (whose binary representation is `100`) and `5` (whose binary representation is `101`). Adding them up we obtain `9`, whose binary representation is `1001` and cannot be represented using only 3 bits. In this case, we need to expect 1 additional bit to the two operands, i.e., we need to take the two operands as two 4-bit integers (`0100` and `0101`). `4` is thus **the conceptual number of bits each quantized integers have**, and we call it `int_bits`, i.e., `element_bits + additional_bits`.

### Meaning of the Variables in `jzf_quantize`

As for the `int_bits` and `element_bits` in `jzf_quantize.py`, they actually have totally different meanings from those mentioned above. To be exact, `int_bits` actually means **how many bits there are in a batch of encrypted integer**, while `element_bits` is a bit complicated:

(i) at first (when it serves as the argument of the function), it is **the same as what we mentioned above**, e.g., at https://github.com/SamuelGong/FLASHE/blob/d18303bbb088bf416c9d81aa1c8a13857867758a/federatedml/secureprotol/jzf_quantize.py#L136

(ii) it then accepts in-place modification with its meaning changed to **the conceptual number of bits that each encrypted integer in a batch has**, e.g., at https://github.com/SamuelGong/FLASHE/blob/d18303bbb088bf416c9d81aa1c8a13857867758a/federatedml/secureprotol/jzf_quantize.py#L137

### Conclusion

I hope that these explanations help you better follow the logic of our code and facilitate your experiments. To improve the readability of `final_big_table.ipynb`, we have just conducted code reframing, please check [it](https://github.com/SamuelGong/FLASHE/blob/d18303bbb088bf416c9d81aa1c8a13857867758a/encrypt_test/final_big_table.ipynb) out and see if it helps, too.
